kind = "api"
previewPath = "/"
title = "Auction Site"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "Django App"
paths = ["/"]

[services.development]
run = "bash /home/runner/workspace/start_django.sh"

[services.production]

[services.production.run]
args = ["bash", "/home/runner/workspace/start_django.sh"]

[services.production.run.env]
PORT = "8000"
REPLIT_DEPLOYMENT = "1"
PYTHONPATH = "/home/runner/workspace"

[services.production.health.startup]
path = "/"
