# Generated by Django 5.2.3 on 2025-10-06 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='seat_limit',
            field=models.PositiveIntegerField(default=10, help_text='Total seats available to participate'),
        ),
        migrations.AddField(
            model_name='auctionparticipant',
            name='requires_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('used', 'Used'), ('unbooked', 'Unbooked')], default='booked', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to='auctions.auctionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'user'], name='auctions_se_item_id_8d7652_idx'), models.Index(fields=['code'], name='auctions_se_code_ea0015_idx')],
            },
        ),
    ]
