# Generated by Django 5.2.3 on 2025-10-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitem_is_settled_auctionitem_seat_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='call_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
