# Generated by Django 5.2.3 on 2025-10-07 08:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='meet_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
