# Generated by Django 5.2.3 on 2025-10-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionitem_meet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionparticipant',
            name='code_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
