# Generated by Django 5.2.x on 2025-10-10
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_userprofile_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='item',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='auctions.auctionitem'),
        ),
    ]
