# Generated by Django 5.2.x
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_payment_item_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient_upi_vpa',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient_bank_holder_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient_bank_account_number',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient_bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
