# Generated by Django 5.2.3 on 2025-10-10 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_tx_id_and_payment_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_debit_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='wallethold',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'item'), name='unique_active_hold_per_user_item'),
        ),
    ]
