# Generated by Django 5.2.3 on 2025-10-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_bankaccount_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='offline_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
