# Generated by Django 5.2.3 on 2026-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_payment_offline_method_payment_payer_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery charge in ₹ (0 = free)', max_digits=8),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='delivery_mode',
            field=models.CharField(choices=[('home_delivery', 'Home Delivery (Courier/Delivery Boy)'), ('self_pickup', 'Self Pickup (Buyer Comes to Seller)'), ('both', 'Both Options Available')], default='home_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='pickup_city',
            field=models.CharField(blank=True, default='', help_text='Pickup city/town', max_length=100),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='pickup_pincode',
            field=models.CharField(blank=True, default='', help_text='Pickup PIN code', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='address',
            field=models.CharField(help_text='Seller ka pickup address (gali/mohalla/colony)', max_length=255),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='seat_limit',
            field=models.PositiveIntegerField(default=0, help_text='Max seats (0 = unlimited)'),
        ),
    ]
